language: node_js

node_js:
  - "5.0"

# Use container-based Travis infrastructure.
sudo: false

addons:
  ssh_known_hosts:
  - 192.241.218.94

branches:
  only:
    - master

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  - openssl aes-256-cbc -K $encrypted_dbf4ccf442cc_key -iv $encrypted_dbf4ccf442cc_iv
    -in deploy_static.pem.enc -out deploy_static.pem -d

install:
  - npm install

script:
  - npm test
  - NODE_ENV=production node_modules/.bin/builder run build-static

after_success:
  # make sure key is permissive, but not too permissive
  - chmod 600 deploy_static.pem
  # clean out any existing staging folder but make sure it exists
  - ssh -i deploy_static.pem formidable@192.241.218.94 "rm -rf static/spectacle-staging && mkdir static/spectacle-staging"
  # copy the spectacle build to the staging arena; if this fails, site is still OK
  - scp -i deploy_static.pem -rp ./build/* formidable@192.241.218.94:/home/formidable/static/spectacle-staging
  # rename the staging arena to the actual spectacle site
  - ssh -i deploy_static.pem formidable@192.241.218.94 "rm -rf static/spectacle && mv static/spectacle-staging/ static/spectacle"
